import Head from 'next/head';
// import Image from 'next/image';
// import { Inter, Pragati_Narrow } from 'next/font/google';

import { Button, DeleteIcon, Typography } from '@/components/mui/index';
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <Heading component='h2' variant="h3">Home Page</Heading>
      <Typography> Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat quia doloremque rerum eius modi unde deserunt? Velit eveniet sequi similique nam magni facilis nemo enim cum reprehenderit, quasi minus quod.</Typography>
        <Button variant='contained'>
          <DeleteIcon />Delete
        </Button>
      </Layout>
    </>
  );
}
